Double quote usage
zendframework/zend-coding-standard pull request #18
Opened 2019-04-30 18:22 UTC by kynx

Squiz.Strings.DoubleQuoteUsage.ContainsVar prevents strings containing variables. This doesn't match the examples in the documentation and, given that PHP7s interpolation uses less memory than concatenation, probably isn't intended.

This PR adds an exclude for that check and tries to make the docs a little more exact.

2019-05-01 05:34 UTC, xtreamwayz commented
> ... given that PHP7s interpolation uses less memory than concatenation ...

I completely missed that part. Here's some in depth review: https://blog.blackfire.io/php-7-performance-improvements-encapsed-strings-optimization.html

2019-05-01 05:39 UTC, geerteltink requested changes

2019-05-01 05:39 UTC, xtreamwayz commented on docs/book/v2/ruleset.md
> +*Invalid: There are no variables, control characters inside double quote strings*
Change to: "Invalid: There are no variables or control characters inside double quote strings."

2019-05-01 05:39 UTC, xtreamwayz commented on docs/book/v2/ruleset.md
> +$string = 'Hello' . ' There' . "\n";
Maybe we should remove this example as interpolation would be better. In this case it would end up the same as the first example: `"Hello There\n";`

2019-05-01 05:43 UTC, xtreamwayz commented
You need to update `test/expected-report.txt` as the report is different after changing the rules. Not sure how I did it, but I guess I ran the tests and just copy pasted `phpcs.log` into that file.

2019-05-01 10:19 UTC, kynx commented
Thanks for the review @xtreamwayz . It'd be worth keeping an eye on https://github.com/squizlabs/PHP_CodeSniffer/issues/2259 for a more comprehensive sniff.

2019-05-01 10:26 UTC, xtreamwayz commented
I saw that this morning. Looks like it's just an idea. No PR yet.

2019-05-01 10:27 UTC, geerteltink approved these changes

2019-05-01 16:22 UTC, Xerkus commented
I believe our rule is that double quoted string can not contain vars or other variable interpolation and `sprintf` should be used instead for reasons related to QA and not performance.
This coding standard rule reflects the rule we've been following in our reviews, so I say it should stay.

2019-05-01 16:42 UTC, weierophinney commented
> I believe our rule is that double quoted string can not contain vars or other variable interpolation and `sprintf` should be used instead for reasons related to QA and not performance.
> This coding standard rule reflects the rule we've been following in our reviews, so I say it should stay.

The main reasons I've advocated usage of `sprintf()` are:

- performance
- readability

Both of these were informed by performance of previous PHP versions with regards to string interpolation. Interpolation was known to be slow, and escaping rules tend to get messy. Concatenation is predictable, but hard to read. `sprintf()` semantics are relatively easy to understand, and generally performant, making it a good solution to these problems. (For the record, `str_replace()` using named placeholders is also quite performant.)

However, if PHP 7 solves most of the performance issues, string interpolation would likely be a viable choice again. As such, I've got an open question to Julien Pauli asking what the performance differences are between the two approaches.

2019-12-31 21:17 UTC, weierophinney commented
This repository has been closed and moved to laminas/laminas-coding-standard; a new issue has been opened at https://github.com/laminas/laminas-coding-standard/issues/4.

2019-12-31 21:17 UTC, weierophinney commented
This repository has been moved to laminas/laminas-coding-standard. If you feel that this patch is still relevant, please re-open against that repository, and reference this issue. To re-open, we suggest the following workflow:
 - Squash all commits in your branch (`git rebase -i origin/{branch}`)
 - Make a note of all changed files (`git diff --name-only origin/{branch}...HEAD
 - Run the laminas/laminas-migration tool on the code.
 - Clone laminas/laminas-coding-standard to another directory.
 - Copy the files from the second bullet point to the clone of laminas/laminas-coding-standard.
 - In your clone of laminas/laminas-coding-standard, commit the files, push to your fork, and open the new PR.
 We will be providing tooling via laminas/laminas-migration soon to help  automate the process.

2023-03-08 01:06 UTC, closed without merging